.TH "/home/dvn/Git-Repository/Linux/LinuxDeviceDriver/sample_1 Directory Reference" 3 "Mon May 25 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dvn/Git-Repository/Linux/LinuxDeviceDriver/sample_1 Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBMajorMinorNumber\&.c\fP"
.br
.RI "\fIThis file implements a smple testing sample module for Major and Minor Number *\&. \fP"
.in -1c
