.TH "/home/dvn/Git-Repository/Linux/LinuxDeviceDriver/sample_0/SampleDrv.c" 3 "Mon May 25 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dvn/Git-Repository/Linux/LinuxDeviceDriver/sample_0/SampleDrv.c \- This file implements a smple testing sample module *\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <linux/module\&.h>\fP
.br
\fC#include <linux/kernel\&.h>\fP
.br
\fC#include <linux/init\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBmodule_init\fP (InitDrv)"
.br
.ti -1c
.RI "\fBmodule_exit\fP (RemoveDrv)"
.br
.ti -1c
.RI "\fBMODULE_LICENSE\fP ('GPL')"
.br
.ti -1c
.RI "\fBMODULE_AUTHOR\fP ('Divin Raj')"
.br
.ti -1c
.RI "\fBMODULE_DESCRIPTION\fP ('Simple Device driver')"
.br
.ti -1c
.RI "\fBMODULE_VERSION\fP ('v\&.1\&.0')"
.br
.in -1c
.SH "Detailed Description"
.PP 
This file implements a smple testing sample module *\&. 


.PP
.IP "\(bu" 2

.IP "\(bu" 2
\fBAuthor:\fP
.RS 4
divinraj1994@gmail.com * 
.RE
.PP

.PP

.SH "Function Documentation"
.PP 
.SS "MODULE_AUTHOR ('Divin Raj')"

.SS "MODULE_DESCRIPTION ('Simple Device driver')"

.SS "module_exit (RemoveDrv)"

.SS "module_init (InitDrv)"

.PP
  Init and Exit Macro * 
.SS "MODULE_LICENSE ('GPL')"

.PP
  Informations * 
.SS "MODULE_VERSION ('v\&.1\&.0')"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
