.TH "/home/dvn/Git-Repository/Linux/LinuxDeviceDriver/sample_2 Directory Reference" 3 "Mon May 25 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dvn/Git-Repository/Linux/LinuxDeviceDriver/sample_2 Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBArgPassing\&.c\fP"
.br
.RI "\fIThis file implements a sample testing programe for passing arguments *\&. \fP"
.in -1c
